# Generated by Django 6.0.3 on 2026-03-13 00:45

import django.db.models.deletion
import pdm.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='文档类型')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='类型代码')),
                ('description', models.TextField(blank=True, verbose_name='类型描述')),
                ('template_path', models.CharField(blank=True, max_length=200, verbose_name='模板路径')),
            ],
            options={
                'verbose_name': '文档类型',
                'verbose_name_plural': '文档类型管理',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='部门代码')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('description', models.TextField(blank=True, verbose_name='部门描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='部门经理')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdm.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门管理',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='产品编码')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('description', models.TextField(verbose_name='产品描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('review', '审核中'), ('approved', '已批准'), ('released', '已发布'), ('obsolete', '已废弃')], default='draft', max_length=20, verbose_name='状态')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本')),
                ('specifications', models.TextField(blank=True, verbose_name='技术规格')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='重量(kg)')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='尺寸')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='材质')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='批准时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_products', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdm.department', verbose_name='负责部门')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_products', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文档标题')),
                ('description', models.TextField(blank=True, verbose_name='文档描述')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('review', '审核中'), ('approved', '已批准'), ('released', '已发布'), ('obsolete', '已废弃')], default='draft', max_length=20, verbose_name='状态')),
                ('file', models.FileField(upload_to=pdm.models.document_upload_path, verbose_name='文档文件')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='文件类型')),
                ('version_comment', models.TextField(blank=True, verbose_name='版本说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdm.document', verbose_name='上一版本')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdm.documenttype', verbose_name='文档类型')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pdm.product', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(max_length=50, unique=True, verbose_name='变更单号')),
                ('title', models.CharField(max_length=200, verbose_name='变更标题')),
                ('description', models.TextField(verbose_name='变更描述')),
                ('change_type', models.CharField(choices=[('product', '产品变更'), ('document', '文档变更'), ('bom', 'BOM变更'), ('other', '其他变更')], max_length=20, verbose_name='变更类型')),
                ('priority', models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高'), (4, '紧急')], default=2, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('reviewing', '审核中'), ('approved', '已批准'), ('rejected', '已拒绝'), ('implemented', '已实施')], default='draft', max_length=20, verbose_name='状态')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='批准时间')),
                ('implemented_at', models.DateTimeField(blank=True, null=True, verbose_name='实施时间')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='要求完成时间')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('implementation_details', models.TextField(blank=True, verbose_name='实施详情')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_changes', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_changes', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewing_changes', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdm.document', verbose_name='关联文档')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdm.product', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': '变更请求',
                'verbose_name_plural': '变更请求管理',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='位置/编号')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='pdm.product', verbose_name='组件')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='pdm.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': 'BOM项',
                'verbose_name_plural': 'BOM物料清单',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='分类代码')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdm.productcategory', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类管理',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdm.productcategory', verbose_name='产品分类'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('message', models.TextField(verbose_name='通知内容')),
                ('notification_type', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('success', '成功')], default='info', max_length=20, verbose_name='通知类型')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='关联对象类型')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '系统通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='pdm_notific_user_id_2e080a_idx'), models.Index(fields=['created_at'], name='pdm_notific_created_f0c10d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['product', 'doc_type'], name='pdm_documen_product_436aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='pdm_documen_status_d999de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('product', 'doc_type', 'version')},
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['request_code'], name='pdm_changer_request_677523_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['status'], name='pdm_changer_status_1deddd_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['change_type'], name='pdm_changer_change__b61a30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bomitem',
            unique_together={('product', 'component')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_code'], name='pdm_product_product_9b2e28_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='pdm_product_status_b83b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='pdm_product_categor_d89944_idx'),
        ),
    ]
