# Generated by Django 6.0.3 on 2026-05-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdm', '0009_word_wordprogress_wrongword'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='词性'),
        ),
        migrations.AddField(
            model_name='word',
            name='phonetic',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='音标'),
        ),
    ]
