# Generated by Django 6.0.3 on 2026-05-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdm', '0010_word_part_of_speech_word_phonetic'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='practice_count',
            field=models.IntegerField(default=0, verbose_name='背诵次数'),
        ),
        migrations.AddField(
            model_name='word',
            name='wrong_count',
            field=models.IntegerField(default=0, verbose_name='错误次数'),
        ),
    ]
